
server:
  port: 8080
spring:
  application:
    name: community-pension-admin
    version: 1.0.0

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      pool-name: HikariCP
      validation-timeout: 5000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      initialization-fail-timeout: 10000
      connection-init-sql: SELECT 1
      connection-timeout: 30000
      auto-commit: on
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/community_pension?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
  jpa:
    open-in-view: true
jwt:
  secret: "cB7ChF1y4Aegk+p9KNkFz0GQeY2e+ZgeIW6EVJbiR9Y="
  expiration: 3600 # 过期时间：1小时
#MyBatis配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-not-delete-value: 1
      logic-delete-value: 0
      logic-delete-field: deleted
  type-aliases-package: com.communitypension.communitypensionadmin.entity
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



