-- 创建健康监测表
CREATE TABLE `health_monitor` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '监测ID',
  `elder_id` bigint NOT NULL COMMENT '老人ID',
  `monitor_type` tinyint NOT NULL COMMENT '监测类型：1-血压，2-血糖，3-体温，4-心率，5-血氧，6-体重，7-其他',
  `systolic_pressure` int DEFAULT NULL COMMENT '收缩压（mmHg）',
  `diastolic_pressure` int DEFAULT NULL COMMENT '舒张压（mmHg）',
  `blood_sugar` double DEFAULT NULL COMMENT '血糖值（mmol/L）',
  `blood_sugar_type` tinyint DEFAULT NULL COMMENT '血糖类型：1-空腹，2-餐后，3-随机',
  `temperature` double DEFAULT NULL COMMENT '体温（℃）',
  `heart_rate` int DEFAULT NULL COMMENT '心率（次/分）',
  `blood_oxygen` int DEFAULT NULL COMMENT '血氧饱和度（%）',
  `weight` double DEFAULT NULL COMMENT '体重（kg）',
  `other_value` varchar(100) DEFAULT NULL COMMENT '其他监测值',
  `monitor_time` datetime NOT NULL COMMENT '监测时间',
  `monitor_result` tinyint NOT NULL COMMENT '监测结果：1-正常，2-偏高，3-偏低，4-异常',
  `remarks` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已删除',
  PRIMARY KEY (`id`),
  KEY `idx_elder_id` (`elder_id`),
  KEY `idx_monitor_type` (`monitor_type`),
  KEY `idx_monitor_time` (`monitor_time`),
  KEY `idx_monitor_result` (`monitor_result`),
  KEY `idx_is_deleted` (`is_deleted`),
  CONSTRAINT `fk_health_monitor_elder` FOREIGN KEY (`elder_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='健康监测表';
