-- 创建服务评价表
CREATE TABLE `service_review` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '评价ID',
  `service_appointment_id` bigint NOT NULL COMMENT '服务预约ID',
  `service_id` bigint NOT NULL COMMENT '服务ID',
  `elder_id` bigint NOT NULL COMMENT '老人ID',
  `review_user_id` bigint NOT NULL COMMENT '评价人ID（老人本人或家属）',
  `review_type` tinyint NOT NULL DEFAULT '0' COMMENT '评价类型：0-老人自己评价，1-家属代评价',
  `rating` int NOT NULL COMMENT '评分（1-5星）',
  `content` varchar(500) DEFAULT NULL COMMENT '评价内容',
  `review_time` datetime NOT NULL COMMENT '评价时间',
  `is_anonymous` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否匿名：0-否，1-是',
  `admin_reply` varchar(500) DEFAULT NULL COMMENT '管理员回复',
  `reply_time` datetime DEFAULT NULL COMMENT '回复时间',
  `reply_admin_id` bigint DEFAULT NULL COMMENT '回复管理员ID',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0-待审核，1-已通过，2-已拒绝',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已删除',
  PRIMARY KEY (`id`),
  KEY `idx_service_id` (`service_id`),
  KEY `idx_elder_id` (`elder_id`),
  KEY `idx_review_user_id` (`review_user_id`),
  KEY `idx_service_appointment_id` (`service_appointment_id`),
  KEY `idx_status` (`status`),
  KEY `idx_is_deleted` (`is_deleted`),
  CONSTRAINT `fk_service_review_service` FOREIGN KEY (`service_id`) REFERENCES `services` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_service_review_elder` FOREIGN KEY (`elder_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_service_review_user` FOREIGN KEY (`review_user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_service_review_appointment` FOREIGN KEY (`service_appointment_id`) REFERENCES `service_appointment` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='服务评价表';
